### PR TITLE
Set up Vagrant

### PR DESCRIPTION
**Pull request by gregkare**
* [x] Add Vagrant config
* [x] Write documentation on how to start the VM

### CODE REVIEW

**Comment by fkooman** [comment]
Thanks!!!

The official Vagrant images of Fedora (23) are available here: https://getfedora.org/en/cloud/download/, there are two flavors, I guess you will target VirtualBox? Would it be difficult to support both libvirt/kvm and VirtualBox?

**Comment by gregkare** [comment]
I've never used libvirt/KVM with Vagrant (in fact I didn't know they were supported). Supporting both should be just two different directives in the config file. I've done it before for VirtualBox and VMware. I'll try the official Fedora 23 images tomorrow!

**Comment by fkooman** [comment]
Cool thanks! I interfered with your README a bit :( I added some instructions for the server/VM myself now without depending on git, no need to have git on production servers :-) You can just add your section to the new README as well!

**Comment by gregkare** [comment]
I've merged the README and updated the base box to Fedora 23

**Comment by fkooman** [comment]
I can merge the pull request if you want? We can create a separate issue for making the script idempotent... but I don't want to riddle it with `if` statements, if we go that way it is better to use something like ansible... What do you think?

**Comment by gregkare** [comment]
Oops, I forgot to delete the idempotence task, it doesn't take long to destroy and recreate the box if needed so it doesn't matter right now.

**Pull request merged**
